version: "3.2"
services:
  ts3:
    image: teamspeak:3.13.6
    environment:
      - TS3SERVER_LICENSE=accept
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: any
    volumes:
      - /home/ts3/data:/var/ts3server
    ports:
      # Server query
      # - published: 10011
      #   target: 10011
      #   protocol: tcp
      #   mode: host
      # Voice
      - published: 9987
        target: 9987
        protocol: udp
        mode: host
