version: "3.2"
services:
  swarm-cronjob:
    image: crazymax/swarm-cronjob:1.10.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Warsaw"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role == manager
  backup:
    image: kbck/backup
    environment:
      - B2_BUCKET=${B2_BUCKET}
      - B2_KEY_ID=${B2_KEY_ID}
      - B2_APP_KEY=${B2_APP_KEY}
    volumes:
      - /home/ts3/data:/var/backups/ts3
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 2 */2 * *"
        - "swarm.cronjob.skip-running=true"
      replicas: 0
      restart_policy:
        condition: none
  ts3:
    image: teamspeak:3.13.6
    environment:
      - TS3SERVER_LICENSE=accept
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: any
    volumes:
      - /home/ts3/data:/var/ts3server
    ports:
      # Server query
      # - published: 10011
      #   target: 10011
      #   protocol: tcp
      #   mode: host
      # Voice
      - published: 9987
        target: 9987
        protocol: udp
        mode: host
